[server]
# Disable the file watcher in deployed environment to prevent excessive resource usage
fileWatcherType = "none"
runOnSave = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[global]
disableWatchdogWarning = true
showWarningOnDirectExecution = false

[theme]
primaryColor = "#217EEC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Force checking for module changes
fastReruns = false